version : "3.8"
services:

  declanmorris:
    container_name: declanmorris
    image: ghcr.io/declan-morris/declanmorris.com:main
    restart: always
    ports:
      - "8080:80"

  whoami:
    container_name: "simple-service"
    image: "traefik/whoami"
    restart: always
    ports:
      - "8085:80"