- name: Install docker python package
  pip:
    name: docker

- name: Install docker-compose python package
  pip:
    name: docker-compose

- name: Install docker python package - required for ansible docker compose
  pip:
    name: docker

- name: Creates docker directory
  file:
    path: /opt/docker
    state: directory