- name: Creates docker directory
  file:
    path: /home/dtm/docker/plex
    state: directory

- name: Copy compose source templates for plex
  template:
    src: files/docker/plex/docker-compose.yml
    dest: /home/dtm/docker/plex/docker-compose.yml
    
- name: Copy env source templates for plex
  template:
    src: files/docker/plex/.env
    dest: /home/dtm/docker/plex/.env

- name: Create and start plex services
  docker_compose:
    project_src: /home/dtm/docker/plex
    pull: yes
  register: output