---

- name: Backup docker containers
  include: docker-traefik.yml


#####

# - name: Install file provider
#   template:
#     src: files/file-provider-main.yml
#     dest: /opt/traefik/traefik/conf/main.yml
#     mode: "{{ docker_compose_file_mask }}"
#     owner: "{{ docker_user.name }}"
#   notify: restart traefik
#   become: true

######