# grog.package
package_list:
  - name: python3
  - name: python3-pip

certbot_auto_renew_user: dtm
certbot_auto_renew_minute: "03"
certbot_auto_renew_hour: "5"
certbot_create_if_missing: true

certbot_auto_renew_options: --quiet --no-self-upgrade --nginx

certbot_create_method: standalone
certbot_create_standalone_stop_services: []
certbot_testmode: false

certbot_certs:
  - domains:
    - declanmorris.com
    - www.declanmorris.com
    - declan-morris.com
    - www.declan-morris.com

certbot_admin_email: "{{ certbot.adminEmail }}"