# # grog.package
package_list:
  - name: sudo #debian doesn't come with sudo
  - name: lshw
  - name: hddtemp
  - name: lm-sensors
  - name: python3
  - name: python3-pip
  - name: tmux
  - name: fdisk
  - name: mergerfs
  - name: ncdu

# telegraf
telegraf_influxdb_urls:
  - http://192.168.86.200:8086

remove_nag: true
remove_enterprise_repo: true
add_no_subscription_repo: true

# output
telegraf_influxdb_v2: true
telegraf_influxdb_token: "{{ influx.token }}"
telegraf_influxdb_organization: "{{ influx.organisation }}"
telegraf_influxdb_bucket: "{{ influx.bucket }}"

telegraf_plugins_base:
  - name: mem
  - name: system
  - name: cpu
    options:
      percpu: "true"
      totalcpu: "true"
      collect_cpu_time: "false"
      report_active: "false"
  - name: diskio
  - name: kernel
  - name: processes
  - name: hddtemp
  - name: sensors

nfs_exports:
  - "/storage/data *(rw,sync,no_root_squash)"

fstab_mergerfs:
  - { source: "/mnt/disk*", mountpoint: "/storage", fs: fuse.mergerfs, opts: "defaults,nonempty,allow_other,use_ino,moveonenospc=true,category.create=mspmfs,dropcacheonclose=true,minfreespace=250G,fsname=jbod" }

snapraid_parity_disks:
  - { path: /mnt/parity1, diskbyid: /dev/disk/by-id/ata-WDC_WD180EDGZ-11B2DA0_3MGKEL6U-part1, fs: ext4, opts: defaults, content: false }

snapraid_data_disks:
  - { path: /mnt/disk1, diskbyid: /dev/disk/by-id/ata-WDC_WD140EDFZ-11A0VA0_9LG2BHVA-part1, fs: ext4, opts: defaults, content: true }

# snapraid
snapraid_config_excludes:
  - "*.unrecoverable"
  - "/tmp/"
  - "/lost+found/"
  - "downloads/"
  - "appdata/"
  - "*.!sync"
  - ".AppleDouble"
  - "._AppleDouble"
  - ".DS_Store"
  - "._.DS_Store"
  - ".Thumbs.db"
  - ".fseventsd"
  - ".Spotlight-V100"
  - ".TemporaryItems"
  - ".Trashes"
  - ".AppleDB"
  - ".nfo"