# # grog.package
package_list:
  - name: bash-completion
  - name: curl
  - name: dnsutils
  - name: fio
  - name: git
  - name: python3
  - name: python3-pip
  - name: gparted
  - name: python-is-python3 # required for acs zsh aliases plugin???

docker_users:
  - dtm

## oh my zsh theme
oh_my_zsh_install: yes
zsh_plugin: ohmyzsh
configureZSH: true

users:
  - username: dtm
    oh_my_zsh:
      plugins:
        - git
        - docker
        - docker-compose
        - thefuck
        - aliases