- name: Creates docker directory for media
  file:
    path: /home/dtm/docker/compose-media
    state: directory

- name: Copy compose source templates for media
  template:
    src: files/docker/media/docker-compose.yml
    dest: /home/dtm/docker/compose-media/docker-compose.yml
    
- name: Copy env source templates for media
  template:
    src: files/docker/media/.env
    dest: /home/dtm/docker/compose-media/.env

- name: Copy tandoor.env source templates
  template:
    src: files/docker/media/.tandoor.env
    dest: /home/dtm/docker/compose-media/.tandoor.env

- name: Creates directory for tandoor
  file:
    path: /home/dtm/docker/tandoor/nginx/conf.d
    state: directory

- name: Copy tandoor nginx conf template
  template:
    src: files/docker/media/tandoor.nginx.conf
    dest: /home/dtm/docker/tandoor/nginx/conf.d/Recipes.conf

- name: Create config directory
  file:
    path: /home/dtm/docker/traefik/
    state: directory

- name: Install config
  template:
    src: files/traefik/traefik.yml
    dest: /home/dtm/docker/traefik/traefik.yml

- name: Create and start media services 
  docker_compose:
    project_src: /home/dtm/docker/compose-media
    pull: yes
  register: output

- name: Prune docker images
  docker_prune:
    images: true