---

- name: Prepare VM for docker
  include: dockerPrepare.yml

- name: Media docker containers
  include: docker-services.yml

# - name: Backup docker containers
#   include: docker-backups.yml

- name: Prep Critical Role Downloads
  include: critRole.yml

- name: Create rclone cronjob to backup paperless documents
  cron:
    name: "rclone paperless backup"
    weekday: "*"
    hour: "*/4"
    minute: "0"
    job: "/usr/local/bin/rclone copy /opt/docker/paperless/data/media/documents gdrive:/paperlessBackup >> /home/dtm/rcloneLog.txt 2>&1"