---

- name: add nginx apt-key
  apt_key: 
    url: http://nginx.org/keys/nginx_signing.key 
    state: present 
  become: true

- name: Add nginx stable repository from PPA and install its signing key on Ubuntu target
  apt_repository:
    repo: deb https://nginx.org/packages/ubuntu/ {{ ansible_distribution_release }} nginx
  become: true  

- name: Update the repository cache and update package "nginx" to latest version
  apt:
    name: nginx
    state: latest

- name: Install and upgrade python3-certbot-nginx
  apt:
    name: python3-certbot-nginx
    state: latest

- name: Copy dmdc nginx conf file
  template:
    # src: files/dmdc.conf
    src: files/dmdc.https.conf
    dest: /etc/nginx/conf.d/dmdc.conf
  register: nginxConfigChanged

- name: Copy whoami nginx conf file
  template:
    src: files/whoami.conf
    dest: /etc/nginx/conf.d/whoami.conf
  register: nginxConfigChanged

- name: remove default site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: copy options-ssl-nginx.conf
  copy: 
    src: /usr/lib/python3/dist-packages/certbot_nginx/_internal/tls_configs/options-ssl-nginx.conf
    dest: /etc/letsencrypt/options-ssl-nginx.conf
    remote_src: yes

- name: Restart nginx
  service: 
    name: nginx 
    state: restarted
  # when: nginxConfigChanged is changed
  ignore_errors: yes