- name: Copy nginx conf file
  template:
    src: files/dmdc.https.conf
    dest: /etc/nginx/conf.d/dmcd.conf
  register: nginxConfigChanged
  
- name: remove default site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Restart nginx
  service: 
    name: nginx 
    state: restarted
  when: nginxConfigChanged is changed
