version : "3.8"
services:

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - 8086:8086
    volumes:
      - ${DOCKERDIR}/influxdb/data:/var/lib/influxdb2
      - ${DOCKERDIR}/influxdb/config:/etc/influxdb2
    environment:
        - DOCKER_INFLUXDB_INIT_MODE=setup
        - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUX_USER}
        - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUX_PASS}
        - DOCKER_INFLUXDB_INIT_ORG=${INFLUX_ORG}
        - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUX_BUCKET}
        - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUX_TOKEN}
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - ${DOCKERDIR}/grafana:/var/lib/grafana
    restart: unless-stopped